### ISSUE TITLE
Read more papers (for Lit. Review)

### ISSUE THREAD

**Issue by sbinabdullah** [sbinabdullah/AToM-issues#1]
Read more papers.

**Comment by rishiad** [comment]
A couple papers that I have recently read: 

- [Voicebox: Text-Guided Multilingual Universal Speech Generation at Scale](https://doi.org/10.48550/arXiv.2306.15687)
- [VoiceCraft: Zero-Shot Speech Editing and Text-to-Speech in the Wild](https://jasonppy.github.io/VoiceCraft_web/)
- [The Annotated S4
Efficiently Modeling Long Sequences with Structured State Spaces](https://srush.github.io/annotated-s4/)

**Comment by sbinabdullah** [comment]
Yo bro - this is for my Advanced Topics project lol 😂. Thanks for the papers tho.
